language: c
compiler:
  - gcc

os:
  - linux

arch:
  - amd64
  - arm64

cache:
  directories:
    - dpdk-dir

addons:
  apt:
    packages:
      - bc
      - libssl-dev

before_install: ./.travis/show-myself.sh

before_script: export PATH=$PATH:$HOME/bin

env:
  - OPTS="--disable-ssl"

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/show-myself.sh

notifications:
  email:
    recipients:
      - Jingzhao.Ni@arm.com
