trigger:
- master

jobs:
- job: build_container
  dependsOn: []
  pool:
    vmImage: 'ubuntu-16.04'
  container: google/cloud-sdk:latest
  steps:
  - bash: |
      echo 11111111111111111111111111111111
      echo 22222222222222222222222222222222

- job: generate_toolchains
  dependsOn: "build_container"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      echo "xxxxxx1111111111111111111111111" >> ./testResult.txt
      pwd
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.StagingDirectory)/testResult.txt"
      artifactName: drop
    condition: always()

- job: dependcheck
  dependsOn: ["build_container","generate_toolchains"]
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(Build.StagingDirectory)'
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 19.03.5
      releaseType: stable
  - bash: |
      echo "start build binary & docker images"
      ./ci/docker_ci.sh
      cat testResult.txt
