trigger:
- master

jobs:
- job: build_container
  strategy:
    matrix:
      ubuntu:
        LINUX_DISTRO: ubuntu
  dependsOn: []
  pool:
    vmImage: 'ubuntu-16.04'
  container: google/cloud-sdk:latest
  steps:
  - bash: |
      apt update
      apt install -y docker.ce
      docker version
      echo 22222222222222222222222222222222
      ./install.sh
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 17.09.0-ce
      releaseType: stable
