trigger:
- master

jobs:
- job: build_container
  strategy:
    matrix:
      ubuntu:
        LINUX_DISTRO: ubuntu
      centos:
        LINUX_DISTRO: centos
  dependsOn: []
  pool:
    vmImage: 'ubuntu-16.04'
  container: google/cloud-sdk:latest
  steps:
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 19.03.5
      releaseType: stable
  - bash: |
      echo 11111111111111111111111111111111
      docker version
      echo 22222222222222222222222222222222
      ./install.sh


- job: generate_toolchains
  dependsOn: "build_container"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: GoTool@0
    inputs:
      version: '1.13.4' 
  - bash: |
      echo "xxxxxxxxxxxxxxxxxxxxxxxxxxx"

- job: release_arm64
  displayName: "Linux-arm64 release.server_only"
  pool: "arm-large"
  steps:
  - bash: |
      echo 3333333333333333333333333333333
      echo 44444444444444444444444444444444444444
      echo 55555555555555555555555555555555555555555555

