trigger:
- master

jobs:
- job: build_container
  strategy:
    matrix:
      ubuntu:
        LINUX_DISTRO: ubuntu
  dependsOn: []
  pool:
    vmImage: 'ubuntu-16.04'
  container: google/cloud-sdk:latest
  steps:
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 19.03.5
      releaseType: stable
  - bash: |
      echo 111111111111111111111111
      docker version
      echo 22222222222222222222222222222222
      ./install.sh
